"""Notification service for managing user notifications."""

from models.notification import NotificationResponse
from repositories.notification_repository import NotificationRepository


class NotificationService:
    """Business logic for notification management.

    Provides read access and mark-as-read operations for
    notifications generated by the observer system.
    """

    @staticmethod
    async def get_notifications(
        user_id: str,
        page: int = 1,
        per_page: int = 20,
        unread_only: bool = False,
    ) -> dict:
        """Get paginated notifications for a user.

        Args:
            user_id: The user's ID.
            page: Page number.
            per_page: Items per page.
            unread_only: Only return unread notifications.

        Returns:
            Paginated response dict.
        """
        from utils.pagination import paginate_params, paginated_response

        params = paginate_params(page, per_page)
        items = await NotificationRepository.find_by_user(
            user_id,
            skip=params["skip"],
            limit=params["limit"],
            unread_only=unread_only,
        )
        total = await NotificationRepository.count_by_user(
            user_id, unread_only,
        )

        notifications = [
            NotificationResponse(**item).model_dump() for item in items
        ]
        return paginated_response(notifications, total, page, per_page)

    @staticmethod
    async def get_unread_count(user_id: str) -> int:
        """Get the count of unread notifications.

        Args:
            user_id: The user's ID.

        Returns:
            Number of unread notifications.
        """
        return await NotificationRepository.count_by_user(
            user_id, unread_only=True,
        )

    @staticmethod
    async def mark_as_read(notification_id: str) -> bool:
        """Mark a notification as read.

        Args:
            notification_id: The notification's ID.

        Returns:
            True if updated.
        """
        return await NotificationRepository.mark_as_read(notification_id)

    @staticmethod
    async def mark_all_read(user_id: str) -> int:
        """Mark all notifications for a user as read.

        Args:
            user_id: The user's ID.

        Returns:
            Number of notifications marked read.
        """
        return await NotificationRepository.mark_all_read(user_id)
